# fly.toml app configuration file generated for repo-stats on 2024-08-23T15:56:44+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "repo-stats"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
